    @include('proposals.show.head')
@include('proposals.show.cards')
@include('proposals.show.client_data')
<br>
@if(!is_null($proposal->send_date))
    @include('proposals.statuses')
@endif
<br>
@include('proposals.show.kit_data')
<br>
@include('proposals.show.staff')
