services:
    mysql:
        image: mysql
        platform: linux/arm64 # Adicione esta linha
        container_name: mysql_db
        ports:
            - "3306:3306"
        volumes:
            - .docker/dbdata:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: Romanini.95!
            MYSQL_DATABASE: seu_banco_principal
        networks:
            - alluz-network

    agent:
        platform: linux/arm64 # Adicione esta linha
        volumes:
            - .:/var/www/html
        build: .
        ports:
            - "8001:80"
        networks:
            - alluz-network

    redis:
        image: redis:latest
        platform: linux/arm64 # Adicione esta linha também
        container_name: redis
        ports:
            - "6379:6379"
        networks:
            - alluz-network

networks:
    alluz-network:
        driver: bridge
