services:
    mysql:
        image: mysql
        platform: linux/arm64
        container_name: mysql_db
        ports:
            - "3306:3306"
        volumes:
            - .docker/dbdata:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: Romanini.95!
            MYSQL_DATABASE: seu_banco_principal
        networks:
            - alluz-network

    agent:
        platform: linux/arm64
        build: .
        ports:
            - "8001:80"
        volumes:
            # Volume para sincronizar o seu código
            - .:/var/www/html
            # MUDANÇA 1: Adiciona o volume para a configuração do Apache
            # Isto corrige os erros "Forbidden" ao apontar para a pasta /public
            - ./.docker/apache/000-default.conf:/etc/apache2/sites-available/000-default.conf
        # MUDANÇA 2: Adiciona a linha de utilizador
        # Isto corrige os problemas de permissão de ficheiros entre o seu Mac e o Docker
        user: "${UID}:${GID}"
        networks:
            - alluz-network

    redis:
        image: redis:latest
        platform: linux/arm64
        container_name: redis
        ports:
            - "6379:6379"
        networks:
            - alluz-network

networks:
    alluz-network:
        driver: bridge
